__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_pvt_small.yml',
]

output_dir: ./output/rtdetr_pvt_small_6x_coco